//
// Created by zjh on 2022/7/17.
//

#ifndef EXERCISENDK_CONSTDEFINE_H
#define EXERCISENDK_CONSTDEFINE_H

#endif //EXERCISENDK_CONSTDEFINE_H

#define STREAM_TYPE 3
#define SAMPLE_RATE 44100
#define CHANNEL_CONFIG (0X4 | 0X8)
#define AUDIO_FORMAT 2
#define MODE 1
